#!/usr/bin/env php
<?php
declare (strict_types=1);

error_reporting(E_ALL);

require 'vendor/autoload.php';

use Chat\Server;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

$application = new Application();

//$application->add(new Server());

$application->run();